{"uuid": "6791452d-312a-44b6-aac6-9a247aa97f3c", "children": ["31394433-e3b8-4b3f-a91f-ab1ff4d41a1d"], "befores": [{"name": "test_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Users\\Administrator\\PycharmProjects\\Framework_POM\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Framework_POM\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 935, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Framework_POM\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Framework_POM_17\\conftest.py\", line 15, in test_setup\n    driver = webdriver.Chrome()\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Framework_POM\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Framework_POM\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1557048404873, "stop": 1557048404874}], "start": 1557048404873, "stop": 1557048405144}